name: Publish NPM package
permissions:
  contents: write
on:
  push:
    tags:
      - '*'
jobs:
  test:
    uses: ./.github/workflows/test.yml # Run tests
  publish:
    runs-on: ubuntu-latest
    needs: [test]  # Require tests to pass before publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Publish NPM package
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
