name: Run tests
permissions:
  contents: write
on:
  push:
  workflow_call: # Allow this workflow to be called from other workflows
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: |
          bun install
          cd test && bun install
      - name: Run tests
        run: bun run test
